# Generated by Django 5.2.17 on 2026-09-24 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$', 'Use 2–10 uppercase letters.')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ticket_counter', serialize=False, to='organizations.organization')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('key__regex', '^[A-Z]{2,10}$')), name='organization_key_format'),
        ),
    ]
