# Generated by Django 5.2.17 on 2026-09-24 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION organizations_key_immutable() RETURNS trigger AS $$
            BEGIN
              IF NEW.key <> OLD.key THEN
                RAISE EXCEPTION 'Organization key is immutable';
              END IF;
              RETURN NEW;
            END $$ LANGUAGE plpgsql;
            CREATE TRIGGER organizations_key_immutable
              BEFORE UPDATE OF key ON organizations_organization
              FOR EACH ROW EXECUTE FUNCTION organizations_key_immutable();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS organizations_key_immutable ON organizations_organization;
            DROP FUNCTION IF EXISTS organizations_key_immutable();
            """,
        )
    ]
