#!/usr/bin/env node

/**
 * CSS Token Generator
 * Converts JavaScript design tokens to CSS custom properties
 *
 * Usage: npm run tokens:generate
 *        or: node scripts/generateCssTokens.js
 */

const fs = require('fs');
const path = require('path');
const { DESIGN_TOKENS } = require('../constants/designTokens');

/**
 * Flatten nested object to CSS variable format
 * { colors: { blue: { 500: '#3b82f6' } } } → { '--color-blue-500': '#3b82f6' }
 */
function flattenTokens(obj, prefix = '') {
  let result = {};

  for (const [key, value] of Object.entries(obj)) {
    const varName = prefix ? `${prefix}-${key}` : key;

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Recursively flatten nested objects
      Object.assign(result, flattenTokens(value, varName));
    } else {
      // Convert to CSS variable name (using kebab-case)
      result[`--${varName}`] = value;
    }
  }

  return result;
}

/**
 * Generate CSS custom properties from design tokens
 */
function generateCssVariables() {
  const output = [];

  // Add header comment
  output.push('/**');
  output.push(' * Design Token CSS Variables');
  output.push(' * AUTO-GENERATED from constants/designTokens.js');
  output.push(' * DO NOT EDIT THIS FILE MANUALLY');
  output.push(' * Run: npm run tokens:generate to regenerate');
  output.push(' *');
  output.push(' * Generated on: ' + new Date().toISOString());
  output.push(' */');
  output.push('');
  output.push(':root {');

  // === PRIMITIVE TOKENS ===

  // Primitive colors
  output.push('  /* === PRIMITIVE COLORS === */');
  const colorVars = flattenTokens({ color: DESIGN_TOKENS.primitives.colors });
  Object.entries(colorVars).sort().forEach(([name, value]) => {
    output.push(`  ${name}: ${value};`);
  });
  output.push('');

  // Spacing
  output.push('  /* === SPACING === */');
  const spacingVars = flattenTokens({ spacing: DESIGN_TOKENS.primitives.spacing });
  Object.entries(spacingVars).sort().forEach(([name, value]) => {
    output.push(`  ${name}: ${value};`);
  });
  output.push('');

  // Typography
  output.push('  /* === TYPOGRAPHY === */');
  Object.entries(DESIGN_TOKENS.primitives.typography).forEach(([size, props]) => {
    output.push(`  --font-size-${size}: ${props.size};`);
    output.push(`  --line-height-${size}: ${props.lineHeight};`);
    output.push(`  --font-weight-${size}: ${props.weight};`);
  });
  output.push('');

  // Border radius
  output.push('  /* === BORDER RADIUS === */');
  const radiusVars = flattenTokens({ radius: DESIGN_TOKENS.primitives.radius });
  Object.entries(radiusVars).sort().forEach(([name, value]) => {
    output.push(`  ${name}: ${value};`);
  });
  output.push('');

  // Shadows
  output.push('  /* === SHADOWS === */');
  const shadowVars = flattenTokens({ shadow: DESIGN_TOKENS.primitives.shadows });
  Object.entries(shadowVars).sort().forEach(([name, value]) => {
    output.push(`  ${name}: ${value};`);
  });
  output.push('');

  // === SEMANTIC TOKENS ===

  // Semantic status tokens
  output.push('  /* === STATUS TOKENS === */');
  Object.entries(DESIGN_TOKENS.semantic.status).forEach(([status, props]) => {
    output.push(`  --status-${status}-bg: ${props.background};`);
    output.push(`  --status-${status}-text: ${props.text};`);
    output.push(`  --status-${status}-border: ${props.border};`);
  });
  output.push('');

  // Semantic priority tokens
  output.push('  /* === PRIORITY TOKENS === */');
  Object.entries(DESIGN_TOKENS.semantic.priority).forEach(([priority, props]) => {
    output.push(`  --priority-${priority}-bg: ${props.background};`);
    output.push(`  --priority-${priority}-text: ${props.text};`);
    output.push(`  --priority-${priority}-border: ${props.border};`);
  });
  output.push('');

  // Semantic role tokens
  output.push('  /* === ROLE TOKENS === */');
  Object.entries(DESIGN_TOKENS.semantic.role).forEach(([role, props]) => {
    output.push(`  --role-${role}-bg: ${props.background};`);
    output.push(`  --role-${role}-text: ${props.text};`);
    output.push(`  --role-${role}-border: ${props.border};`);
  });
  output.push('');

  // Intent tokens (buttons, alerts)
  output.push('  /* === INTENT TOKENS === */');
  Object.entries(DESIGN_TOKENS.semantic.intent).forEach(([intent, props]) => {
    output.push(`  --intent-${intent}-bg: ${props.background};`);
    output.push(`  --intent-${intent}-hover: ${props.hover};`);
    output.push(`  --intent-${intent}-text: ${props.text};`);
  });
  output.push('');

  output.push('}');
  output.push('');

  // Add dark mode placeholder (for future use)
  output.push('/* === DARK MODE (Future) === */');
  output.push('@media (prefers-color-scheme: dark) {');
  output.push('  :root {');
  output.push('    /* Dark mode token overrides will be implemented here */');
  output.push('  }');
  output.push('}');
  output.push('');

  return output.join('\n');
}

/**
 * Main execution
 */
function main() {
  try {
    // Generate CSS content
    const cssContent = generateCssVariables();

    // Determine output path
    const outputPath = path.join(__dirname, '..', 'public', 'css', 'design-tokens.css');

    // Create directory if it doesn't exist
    const dirPath = path.dirname(outputPath);
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }

    // Write CSS file
    fs.writeFileSync(outputPath, cssContent, 'utf8');

    // Calculate statistics
    const variableCount = (cssContent.match(/^  --/gm) || []).length;
    const fileSizeKb = (cssContent.length / 1024).toFixed(2);

    // Print success message
    console.log('');
    console.log('✅ Design Tokens Generated Successfully');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`📁 Output:      ${outputPath}`);
    console.log(`📊 Variables:   ${variableCount}`);
    console.log(`💾 File Size:   ${fileSizeKb} KB`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');
    console.log('📝 Include in your HTML:');
    console.log('   <link rel="stylesheet" href="/css/design-tokens.css">');
    console.log('');
    console.log('🎨 Use in CSS:');
    console.log('   background: var(--status-open-bg);');
    console.log('   color: var(--status-open-text);');
    console.log('');

  } catch (error) {
    console.error('❌ Error generating CSS tokens:');
    console.error(error.message);
    process.exit(1);
  }
}

// Run if executed directly
if (require.main === module) {
  main();
}

module.exports = { generateCssVariables, flattenTokens };
